# This file was generated by GoReleaser. DO NOT EDIT.
cask "get-out" do
  version "1.3.0"

  on_macos do
    on_intel do
      url "https://github.com/jflowers/get-out/releases/download/v#{version}/get-out_#{version}_darwin_amd64.tar.gz"
      sha256 "8729c611ed52c2884754a2896e0c68c0a30f4119c333f77d2e5d27350cff03c9"
    end
    on_arm do
      url "https://github.com/jflowers/get-out/releases/download/v#{version}/get-out_#{version}_darwin_arm64.tar.gz"
      sha256 "b7e1fd457dafc2c1df089b3ce926f9eaaa50fbf21639e5625e879b4bc3e6745a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jflowers/get-out/releases/download/v#{version}/get-out_#{version}_linux_amd64.tar.gz"
      sha256 "8bc1763eea4a86b0eecadf06db35ad8cf492af331a7e113fa0f5cb9df71e2a86"
    end
    on_arm do
      url "https://github.com/jflowers/get-out/releases/download/v#{version}/get-out_#{version}_linux_arm64.tar.gz"
      sha256 "b994d4e3c4a3ab38eadd54b69c008761c6a396a000e7f64ff7d77f90f0e78082"
    end
  end

  name "get-out"
  desc "Export Slack messages (DMs, groups, channels) to organized Google Docs"
  homepage "https://github.com/jflowers/get-out"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "get-out"
  manpage "man/get-out.1"

  # No zap stanza required

end
