# This file was generated by GoReleaser. DO NOT EDIT.
cask "get-out" do
  name "get-out"
  desc "Export Slack messages (DMs, groups, channels) to organized Google Docs"
  homepage "https://github.com/jflowers/get-out"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "get-out"
  manpage "man/get-out.1"

  on_macos do
    on_intel do
      url "https://github.com/jflowers/get-out/releases/download/v#{version}/get-out_#{version}_darwin_amd64.tar.gz"
      sha256 "8bdd646acfa3886ff8cdb54297851921ffcea67d0df340e79224f458b66ee7b5"
    end
    on_arm do
      url "https://github.com/jflowers/get-out/releases/download/v#{version}/get-out_#{version}_darwin_arm64.tar.gz"
      sha256 "ca79d95c115a6ca6a4a9b77b0717bbdec6fc85116d699cf731988291a6cc896d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jflowers/get-out/releases/download/v#{version}/get-out_#{version}_linux_amd64.tar.gz"
      sha256 "40617804cc9837daedf6287e0daeea56b679f3d2649ff83bd7f66b0d3ad984d3"
    end
    on_arm do
      url "https://github.com/jflowers/get-out/releases/download/v#{version}/get-out_#{version}_linux_arm64.tar.gz"
      sha256 "3ad8214b86f78ea2f17046a0c29572c9320c107c2a90556b310e95449e3e7f2b"
    end
  end

  # No zap stanza required
end
